// GENERATED from paper/round1.tex by scripts/tex-to-paper.js on 2026-10-01T18:19:36.001Z.
// Edit the .tex file (and paper/instructions.txt), then run `npm run paper`. Do not edit this file by hand.
// Multiple-choice answer key, used only by scripts. Never sent to browsers.
export const MCQ_KEY = {"1":"B","2":"C","3":"D","4":"A","5":"E","6":"C","7":"B"};
export const MCQ_POINTS = {"1":2,"2":2,"3":2,"4":2,"5":2,"6":2,"7":2};
