// GENERATED from paper/round1.tex by scripts/tex-to-paper.js on 2026-10-01T18:19:36.001Z.
// Edit the .tex file (and paper/instructions.txt), then run `npm run paper`. Do not edit this file by hand.
export const PAPER = {
  "id": "round1",
  "title": "Kenya Informatics Olympiad 2026",
  "round": "Round 1",
  "instructions": [
    "You have <b>2 hours 30 minutes</b>. The timer at the top of the screen is the official clock, and the paper closes automatically when it reaches zero.",
    "The paper has <b>20 problems</b> in three sections, worth <b>100 marks</b> in total.",
    "<b>Section A</b> (Problems 1–7) is multiple choice. Pick one option. Wrong answers do not lose marks.",
    "<b>Section B</b> (Problems 8–14) needs written answers. Show your working in each box; working earns partial credit.",
    "<b>Section C</b> (Problems 15–20) asks you to describe algorithms. Explain the key idea, the steps, why it is correct, and the running time. You do not need to write code.",
    "Your answers save automatically. You can move between problems and change answers at any time before you submit.",
    "Not sure about a problem? Click <b>Come back to this later</b> under it. An orange dot appears on that problem's number in the list on the left, so you can find it again. It is only a reminder for you and does not affect your marks.",
    "Stay on this page. Leaving it, switching tabs, and pasting text from elsewhere are recorded.",
    "<b>Any form of cheating leads to immediate disqualification.</b> This includes using other websites, AI tools or calculators, getting help from another person, and sharing answers."
  ],
  "money": {
    "title": "Old British money (Sections A and B)",
    "rows": [
      [
        "1 pound (£1)",
        "20 shillings (20s)",
        "1 crown",
        "5s"
      ],
      [
        "1 shilling (1s)",
        "12 pence (12d)",
        "1 half-crown",
        "2s 6d"
      ],
      [
        "1 penny (1d)",
        "4 farthings",
        "1 florin",
        "2s"
      ],
      [
        "1 half-sovereign",
        "10s",
        "1 double florin",
        "4s"
      ]
    ],
    "note": "So, for example, 8s 4d $= 8\\times 12 + 4 = 100$ pence."
  },
  "sections": [
    {
      "id": "A",
      "title": "Multiple Choice",
      "marksNote": "7 problems, 2 marks each",
      "money": true,
      "problems": [
        {
          "id": "1",
          "marks": 2,
          "type": "mcq",
          "text": "A gentleman hands over a crown at the post office. He asks for some twopenny stamps, six times as many penny stamps, and the rest of the money in twopence-halfpenny stamps. How many stamps of each kind (twopenny, penny, twopence-halfpenny) does he receive?",
          "options": [
            "4, 24, 11",
            "5, 30, 8",
            "3, 18, 14",
            "6, 36, 5",
            "2, 12, 17"
          ]
        },
        {
          "id": "2",
          "marks": 2,
          "type": "mcq",
          "text": "A gentleman meets three people asking for help, one after another. To the first he gives 1d more than half the money in his pocket; to the second, 2d more than half of what is left; to the third, 3d more than half of what is then left. He finishes with exactly 1d. How much did he start with?",
          "options": [
            "2s 6d",
            "3s 0d",
            "3s 6d",
            "4s 2d",
            "5s 0d"
          ]
        },
        {
          "id": "3",
          "marks": 2,
          "type": "mcq",
          "text": "A group of cyclists agree to split a bill of £4 equally. By the time the bill is paid, two of them have left, so each cyclist who remains pays 2s more than his original share. How many cyclists were there at the start?",
          "options": [
            "5",
            "6",
            "8",
            "10",
            "12"
          ]
        },
        {
          "id": "4",
          "marks": 2,
          "type": "mcq",
          "text": "A man buys exactly 100 eggs of three qualities, costing 5d, 1d and $\\tfrac12$d each. He buys at least one egg of every quality, pays exactly 8s 4d, and buys the same number of eggs of two of the qualities. How many eggs does he buy at 5d, 1d and $\\tfrac12$d respectively?",
          "options": [
            "10, 10, 80",
            "8, 20, 72",
            "12, 12, 76",
            "5, 5, 90",
            "20, 20, 60"
          ]
        },
        {
          "id": "5",
          "marks": 2,
          "type": "mcq",
          "text": "A grocer weighs out two 1-pound parcels of sugar per minute. A draper cuts three 1-yard lengths of cloth per minute. Each must produce 48 items. Customers interrupt them for 9 minutes in total between the two of them, and the draper is interrupted for 17 times as long as the grocer. Which statement is true?",
          "options": [
            "The grocer finishes 1 minute before the draper.",
            "The grocer finishes 8 minutes before the draper.",
            "The draper finishes 1 minute before the grocer.",
            "The draper finishes $8\\tfrac12$ minutes before the grocer.",
            "They finish at exactly the same time."
          ],
          "long": true
        },
        {
          "id": "6",
          "marks": 2,
          "type": "mcq",
          "text": "Hodge, Jakes and Durrant meet at a cattle market. Hodge says to Jakes: “I’ll give you six of my pigs for one of your horses, and then you’ll have twice as many animals as I have.” Durrant says to Hodge: “I’ll give you fourteen of my sheep for a horse, and then you’ll have three times as many animals as I.” Jakes says to Durrant: “I’ll give you four cows for a horse, and then you’ll have six times as many animals as I have.” Each offer is considered on its own, starting from the original herds. How many animals did Hodge, Jakes and Durrant bring?",
          "options": [
            "7, 11, 21",
            "9, 3, 18",
            "11, 7, 21",
            "13, 11, 23",
            "21, 7, 11"
          ]
        },
        {
          "id": "7",
          "marks": 2,
          "type": "mcq",
          "text": "A man leaves instructions that exactly 55s be shared out once a year among the poor of his parish: 18d to each woman and a half-crown to each man. Every year at least one man and at least one woman must receive money, and no two years may use the same numbers of men and women. For how many years can the charity run?",
          "options": [
            "6",
            "7",
            "8",
            "11",
            "22"
          ]
        }
      ]
    },
    {
      "id": "B",
      "title": "Written Answers",
      "marksNote": "7 problems, 36 marks",
      "money": true,
      "problems": [
        {
          "id": "8",
          "marks": 5,
          "type": "written",
          "text": "Four brothers, John, William, Charles and Thomas, each have a money-box. If John had 2s more, William 2s less, Charles twice as much and Thomas half as much, all four would have the same amount.<p>Together the boxes hold 45s in exactly <b>six coins</b>. The coins available are the sovereign (20s), half-sovereign (10s), crown (5s), double florin (4s), half-crown (2s 6d), florin (2s), shilling, sixpence and threepence.</p>",
          "parts": [
            {
              "id": "a",
              "marks": 2,
              "text": "How much money is in each box?"
            },
            {
              "id": "b",
              "marks": 3,
              "text": "Which coins are in each box?"
            }
          ]
        },
        {
          "id": "9",
          "marks": 6,
          "type": "written",
          "text": "Hiram B. Judkins has five droves of animals, all the same size, made up of oxen, pigs and sheep (at least one of each kind overall). He sells every animal to eight dealers, who each buy the same number of animals. He is paid &#36;17 per ox, &#36;4 per pig and &#36;2 per sheep, and receives exactly &#36;301.",
          "parts": [
            {
              "id": "a",
              "marks": 2,
              "text": "What is the greatest number of animals he could have had?"
            },
            {
              "id": "b",
              "marks": 4,
              "text": "Give <em>every</em> possible combination of oxen, pigs and sheep for that total."
            }
          ]
        },
        {
          "id": "10",
          "marks": 5,
          "type": "written",
          "text": "An Englishman in New York buys goods costing 34 cents. All he has is a dollar (100 c), a three-cent piece and a two-cent piece. The shopkeeper has only a half-dollar (50 c) and a quarter-dollar (25 c). Another customer offers to help and puts down two dimes (10 c each), a five-cent piece, a two-cent piece and a one-cent piece.<p>The coins can be swapped around so that the Englishman pays exactly 34 c and the helpful customer ends up with exactly the money he started with.</p>",
          "parts": [
            {
              "id": "a",
              "marks": 1,
              "text": "How much money does each of the three people hold once the deal is done?"
            },
            {
              "id": "b",
              "marks": 4,
              "text": "Which coins does each person end up with?"
            }
          ]
        },
        {
          "id": "11",
          "marks": 5,
          "type": "written",
          "text": "",
          "parts": [
            {
              "id": "a",
              "marks": 1,
              "text": "A coin lies flat on a table. What is the greatest number of coins of the same size that can be placed flat around it so that each touches it (and none overlap)? Explain why."
            },
            {
              "id": "b",
              "marks": 2,
              "text": "A half-crown has diameter 32 mm and a threepenny piece has diameter 15 mm. What is the greatest number of threepenny pieces that can lie flat on a half-crown, with none overlapping another or reaching beyond the edge? Justify your answer."
            },
            {
              "id": "c",
              "marks": 2,
              "text": "What is the largest diameter a threepenny piece could have for <em>three</em> of them to fit on the half-crown? Give an exact answer."
            }
          ]
        },
        {
          "id": "12",
          "marks": 5,
          "type": "written",
          "text": "A millionaire wants to give away exactly &#36;1 000 000. Each gift must be &#36;1 or a power of 7 (&#36;7, &#36;49, &#36;343, …), and no amount may be given to more than six people.",
          "parts": [
            {
              "id": "a",
              "marks": 2,
              "text": "How many people receive a gift, and how many receive each amount?"
            },
            {
              "id": "b",
              "marks": 2,
              "text": "Explain why there is only one way to do it."
            },
            {
              "id": "c",
              "marks": 1,
              "text": "How many people would receive a gift if he gave away &#36;1 000 000 000 under the same rules?"
            }
          ]
        },
        {
          "id": "13",
          "marks": 5,
          "type": "written",
          "text": "Take an amount £$a$ $s$s $d$d in which the number of pounds is greater than the number of pence ($a > d$; zero shillings or pence are allowed). Its <em>reversal</em> is the amount with $d$ pounds, $s$ shillings and $a$ pence, i.e. $240d + 12s + a$ pence (so $a$ may be 12 or more here).<p>Now apply this rule:</p><ol><li>Subtract the reversal from the original amount, and write the difference in pounds, shillings and pence in the usual way (shillings 0–19, pence 0–11).</li><li>Add the difference to its own reversal.</li></ol><p>For amounts with fewer than £12 the result is always £12 18s 11d.</p>",
          "parts": [
            {
              "id": "a",
              "marks": 1,
              "text": "Check the rule for £7 3s 2d."
            },
            {
              "id": "b",
              "marks": 1,
              "text": "Show that the difference in step 1 is always $239(a-d)$ pence."
            },
            {
              "id": "c",
              "marks": 1,
              "text": "Without the “fewer than £12” condition, what is the smallest amount for which the result is <em>not</em> £12 18s 11d?"
            },
            {
              "id": "d",
              "marks": 2,
              "text": "What is the largest amount for which the result <em>is</em> £12 18s 11d?"
            }
          ]
        },
        {
          "id": "14",
          "marks": 5,
          "type": "written",
          "text": "An excursion ticket costs 19s 9d. The coins in use are: farthing, halfpenny, penny, threepence, sixpence, shilling, florin, half-crown, double florin, crown and half-sovereign. Two payments are different if they use a different number of some coin (the order of the coins does not matter).",
          "parts": [
            {
              "id": "a",
              "marks": 1,
              "text": "In how many ways can you pay 3d?"
            },
            {
              "id": "b",
              "marks": 2,
              "text": "In how many ways can you pay 6d?"
            },
            {
              "id": "c",
              "marks": 2,
              "text": "Describe an efficient method for counting the ways to pay any amount, and explain why it does not count the same payment twice."
            }
          ]
        }
      ]
    },
    {
      "id": "C",
      "title": "Algorithm Design",
      "marksNote": "6 problems, 50 marks",
      "money": false,
      "intro": "For each problem in this section, write an <b>algorithm description</b>, not a program. A full answer explains the key observation, lists the steps of the algorithm, argues why it gives the right answer, and states the time complexity. The constraints tell you how fast your method needs to be.",
      "problems": [
        {
          "id": "15",
          "marks": 5,
          "type": "algo",
          "text": "You are given a string $s$ of $n$ lowercase letters and a letter $c$. In one move you may pick any position $i$ and replace $s_i$ with the letter $c$. (You may only ever write the letter $c$.)<p>Find the minimum number of moves needed to turn $s$ into a palindrome, i.e. a string that reads the same forwards and backwards.</p>",
          "constraints": "$1 \\le n \\le 2\\cdot 10^5$.",
          "example": "$s = \\texttt{kenya}$, $c = \\texttt{a}$. The answer is $3$: change $s_1$, $s_2$ and $s_4$ to <code>a</code>, giving <code>aanaa</code>."
        },
        {
          "id": "16",
          "marks": 8,
          "type": "algo",
          "text": "The <em>mode</em> of an array is the value that appears most often; if several values tie, the mode is the largest of them. For example, the mode of $[1,1,2]$ is $1$ and the mode of $[3,4]$ is $4$.<p>You are given an array $a$ of $n$ positive integers. You may rearrange its elements in any order. Find an arrangement that makes the sum of the modes of all $n$ prefixes as large as possible, and output that arrangement.</p>",
          "constraints": "$1 \\le n \\le 2\\cdot 10^5$, $1 \\le a_i \\le 10^9$.",
          "example": "$a = [2,5,2,5,5,1]$. The arrangement $[5,2,1,5,2,5]$ has mode $5$ for every prefix, giving the maximum possible sum $30$."
        },
        {
          "id": "17",
          "marks": 9,
          "type": "algo",
          "text": "A treasury has $n$ piles of coins; pile $i$ holds $a_i$ coins. A pirate holds a number $x$ and steals as follows:<ol><li>He picks a pile $i$ with $a_i > 0$ and $\\gcd(a_i, x) \\ne 1$. If no such pile exists, he stops.</li><li>Let $g = \\gcd(a_i, x)$. He takes exactly $g$ coins from pile $i$ (so $a_i$ decreases by $g$) and then sets $x = g$.</li><li>He repeats from step 1.</li></ol><p>Find the maximum total number of coins he can steal.</p>",
          "constraints": "$1 \\le n \\le 2\\cdot 10^5$, $1 \\le a_i \\le 3\\cdot 10^5$, $2 \\le x \\le 3\\cdot 10^5$.",
          "example": "$x = 6$, $a = [4, 9, 10]$. The answer is $14$: he can empty the piles of $4$ and $10$ coins."
        },
        {
          "id": "18",
          "marks": 9,
          "type": "algo",
          "text": "An array $b_1, \\dots, b_m$ is a <em>hill</em> if for some position $k$ it strictly increases up to $b_k$ and strictly decreases after it: $b_1 < \\dots < b_k > b_{k+1} > \\dots > b_m$. (A purely increasing or purely decreasing array is also a hill.)<p>You are given an array $a$ of $n$ distinct integers. In one operation you may swap $a_i$ and $a_{i+2}$ for any $i$. Decide whether $a$ can be turned into a hill using any number of operations.</p>",
          "constraints": "$1 \\le n \\le 2\\cdot 10^5$.",
          "example": "$[2,4,1,3,5]$: <b>YES</b> (for instance $[2,4,5,3,1]$ can be reached). &nbsp; $[1,3,2,4]$: <b>NO</b>."
        },
        {
          "id": "19",
          "marks": 9,
          "type": "algo",
          "text": "A binary string is <em>clean</em> if all its characters are equal. In one move you may choose a clean substring (a block of equal characters) and flip every character in it ($0 \\leftrightarrow 1$). The <em>beauty</em> of a string is the minimum number of moves needed to make the whole string clean. The <em>power</em> of a string is the sum of the beauties of all its substrings.<p>You are given a binary string $s$ of length $n$, followed by $q$ updates. Each update gives a position $i$ and flips $s_i$. Output the power of $s$ before any update and after every update.</p>",
          "constraints": "$1 \\le n, q \\le 2\\cdot 10^5$.",
          "example": "$s = \\texttt{0110}$ has power $5$. After flipping position $1$ the string is <code>1110</code>, whose power is $3$."
        },
        {
          "id": "20",
          "marks": 10,
          "type": "algo",
          "text": "For an array $b$ of $m$ integers, a <em>transformation</em> does the following: write down $b_i \\oplus b_j$ for every pair $i < j$ (where $\\oplus$ is bitwise XOR), and replace the array with the $m$ smallest values written.<p>You are given an array $a$ of $n$ non-negative integers and $q$ queries. Each query gives a number $k$; answer with $\\max(a) - \\min(a)$ after applying the transformation $k$ times to the <em>original</em> array.</p>",
          "constraints": "$6 \\le n \\le 1000$, $0 \\le a_i < 2^{30}$, $1 \\le q \\le 2\\cdot 10^5$, $0 \\le k \\le 10^9$.",
          "example": "$a = [6,7,8,9,15,1]$. The arrays after $0,1,2,3$ transformations are $[1,6,7,8,9,15]$, $[1,1,6,6,7,7]$, $[0,0,0,1,1,1]$ and $[0,0,0,0,0,0]$, so the answers for $k = 0, 1, 2$ and any $k \\ge 3$ are $14, 6, 1$ and $0$."
        }
      ]
    }
  ]
};

// Every answer field the server will accept, e.g. "1", "8a", "15".
export const answerKeysOf = p => new Set(p.sections.flatMap(s => s.problems.flatMap(q =>
  q.type === 'written' ? q.parts.map(pt => q.id + pt.id) : [q.id])));
export const ANSWER_KEYS = answerKeysOf(PAPER);
